import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";
import Navbar2 from "./components/Navbar2";
import HomeBanner from "./components/HomeBanner";
import InfoBar from "./components/InfoBar";
import Categories from "./components/Categories";
import GoldPoster from "./components/GoldPoster";
import OriginalBrands from "./components/OriginalBrands";
import Products from "./components/Products";
import Footer from "./components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        <Navbar2/>
        <HomeBanner/>
        <InfoBar/>
        <Categories/>
        <GoldPoster/>
        <OriginalBrands/>
        <Products/>
        <Footer/>
        {children}
      </body>
    </html>
  );
}
